# For all options see https://github.com/bbatsov/rubocop/tree/master/config

inherit_gem:
  gc_ruboconfig: rubocop.yml

AllCops:
  TargetRubyVersion: 3.1.0
  DisplayCopNames: true

Layout/LineLength:
  Max: 100
  Exclude:
    - "Gemfile"

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

RSpec/NestedGroups:
  Max: 8

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/Rails/AvoidSetupHook:
  Enabled: true

# Disabled as it's breaking dependabot 
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'bucket_store.gemspec'

# Disabled as it's breaking rubocop, see:
# https://github.com/rubocop/rubocop/issues/10208
# https://github.com/rubocop/rubocop/issues/10210
Layout/DotPosition:
  Enabled: false
