version: '3'
services:
  minio:
    image: quay.io/minio/minio
    entrypoint: "/bin/bash"
    command: |-
      -c "mkdir -p /data/bucket && minio server /data --console-address \":9001\""
    hostname: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION_NAME: us-east-1
    ports:
      - "9000:9000"
  gcp-simulator:
    image: fsouza/fake-gcs-server
    hostname: gcp
    environment:
      PORT: 9023
    entrypoint: "/bin/sh"
    command: |-
      -c "mkdir -p /data/bucket && /bin/fake-gcs-server -scheme=http -backend=filesystem -filesystem-root=/data -port=9023"
    ports:
      - "9023:9023"
