version: 2.1

references:
  bundle_install: &bundle_install
    run:
      name: Bundle
      command: |
        gem install bundler --no-document && \
        bundle config set no-cache 'true' && \
        bundle config set jobs '4' && \
        bundle config set retry '3' && \
        bundle install

  cache_bundle: &cache_bundle
    save_cache:
      key: bundle-<< parameters.ruby_version >>-{{ checksum "bucket_store.gemspec" }}-{{ checksum "Gemfile" }}
      paths:
        - vendor/bundle

  restore_bundle: &restore_bundle
    restore_cache:
      key: bundle-<< parameters.ruby_version >>-{{ checksum "bucket_store.gemspec" }}-{{ checksum "Gemfile" }}

jobs:
  code_quality:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby_version >>
    steps:
      - add_ssh_keys
      - checkout
      - *restore_bundle
      - *bundle_install
      - *cache_bundle
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby_version >>
    steps:
      - add_ssh_keys
      - checkout
      - *restore_bundle
      - *bundle_install
      - *cache_bundle
      - run:
          name: Run specs
          command: bundle exec rspec

  integration:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby_version >>
      - image: quay.io/minio/minio
        environment:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
          MINIO_REGION_NAME: us-east-1
        entrypoint: /bin/bash
        command: -c "mkdir -p /data/bucket && minio server /data --console-address \":9001\""
    steps:
      - add_ssh_keys
      - checkout
      - *restore_bundle
      - *bundle_install
      - *cache_bundle
      - run:
          name: Run specs
          command: bundle exec rspec --tag integration

workflows:
  version: 2
  tests:
    jobs:
      - code_quality:
          matrix:
            parameters:
              ruby_version: ["3.0", "3.1"]
      - rspec:
          matrix:
            parameters:
              ruby_version: ["2.6", "2.7", "3.0", "3.1"]
      - integration:
          matrix:
            parameters:
              ruby_version: ["2.6", "2.7", "3.0", "3.1"]
