version: 2.1

references:
  bundle_install: &bundle_install
    run:
      name: Bundle
      command: |
        gem install bundler --no-document && \
        bundle config set no-cache 'true' && \
        bundle config set jobs '4' && \
        bundle config set retry '3' && \
        bundle install

  cache_bundle: &cache_bundle
    save_cache:
      key: bundle-{{ checksum ".ruby-version" }}-{{ checksum "file_storage.gemspec" }}-{{ checksum "Gemfile" }}
      paths:
        - vendor/bundle

  restore_bundle: &restore_bundle
    restore_cache:
      key: bundle-{{ checksum ".ruby-version" }}-{{ checksum "file_storage.gemspec" }}-{{ checksum "Gemfile" }}


jobs:
  code_quality:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - add_ssh_keys
      - checkout
      - *restore_bundle
      - *bundle_install
      - *cache_bundle
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - add_ssh_keys
      - checkout
      - *restore_bundle
      - *bundle_install
      - *cache_bundle
      - run:
          name: Run specs
          command: bundle exec rspec

workflows:
  version: 2
  tests:
    jobs:
      - code_quality
      - rspec
